######################################################################
# Automatically generated by qmake (3.0) Sat Jan 7 13:57:30 2017
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .
QT += testlib
QT += core
QT += widgets

CONFIG += testcase

# Input
SOURCES += tutorial4.cpp
